name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: install
      run: |
        pip install .
    - name: Check package installation
      run: |
        python -c "import sys, collective_trace; print('collective_trace path:', collective_trace.__file__); print('sys.path:', sys.path)"
    - name: Test
      run: |
        PYTHONPATH=../ torchrun --nproc_per_node=4 tests/test_in_cpu.py --sync_mode
        PYTHONPATH=../ torchrun --nproc_per_node=4 tests/test_in_cpu.py
